fix(workers): improve video download reliability
#### Context

In some cases video downloads fail due to TLS challenge.
In the log we can see that the download failed, but not why it failed.
In a test environment yt-dlp outputs the error to stderr, but that
doesn't get logged.
```
ERROR: [generic] Got HTTP Error 403 caused by Cloudflare anti-bot challenge; try again with  --extractor-args "generic:impersonate"
```
Adding the extractor arguments fails differently, indicating that the installed version of yt-dl is missing a dependency.
Per https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#impersonation the suggested dependency is curl-cffi.

#### Fix

* Replace the binary version of yt-dlp with a version that includes curl-cffi.
* Include the actual yt-dlp error in the log. That detail is logged at the debug level.

**Note:** for the fix to take effect, manually including the extractor arguments in CRAWLER_YTDLP_ARGS is still required.